inherits = "base16_default"
[pallete]

default = "#101317"
black = "#3ba1ce"
red = "#73a7dc"
green = "#8fe38f"
yellow = "#9ad2e6"
blue = "#b9eded"
magenta = "#c6e2f0"
cyan = "#e3e8e9"
gray = "#9ea2a3"
light-red = "#3ba1ce"
light-green = "#73a7dc"
light-yellow = "#8fe38f"
light-blue = "#9ad2e6"
light-magenta = "#b9eded"
light-cyan = "#c6e2f0"
