inherits = "base16_default"
[pallete]

default = "#2E3440"
black = "#88C0D0"
red = "#BF616A"
green = "#5E81AC"
yellow = "#EBCB8B"
blue = "#A3BE8C"
magenta = "#D08770"
cyan = "#E5E9F0"
gray = "#4C566A"
light-red = "#88C0D0"
light-green = "#BF616A"
light-yellow = "#5E81AC"
light-blue = "#EBCB8B"
light-magenta = "#A3BE8C"
light-cyan = "#D08770"
