inherits = "base16_default"
[pallete]

default = "#101010"
black = "#7c7c7c"
red = "#8e8e8e"
green = "#a0a0a0"
yellow = "#686868"
blue = "#747474"
magenta = "#868686"
cyan = "#b9b9b9"
gray = "#525252"
light-red = "#7c7c7c"
light-green = "#8e8e8e"
light-yellow = "#a0a0a0"
light-blue = "#686868"
light-magenta = "#747474"
light-cyan = "#868686"
