inherits = "base16_default"
[pallete]

default = "#0d0c0a"
black = "#d5c857"
red = "#d48d54"
green = "#e08686"
yellow = "#eaaeb4"
blue = "#ecb5b5"
magenta = "#f2cbd4"
cyan = "#eee7e5"
gray = "#a6a1a0"
light-red = "#d5c857"
light-green = "#d48d54"
light-yellow = "#e08686"
light-blue = "#eaaeb4"
light-magenta = "#ecb5b5"
light-cyan = "#f2cbd4"
