inherits = "base16_default"
[pallete]

default = "#0d0d0d"
black = "#cf4640"
red = "#d6635f"
green = "#d86f63"
yellow = "#c832b3"
blue = "#e09a83"
magenta = "#db7e71"
cyan = "#e2d1cd"
gray = "#9e928f"
light-red = "#cf4640"
light-green = "#d6635f"
light-yellow = "#d86f63"
light-blue = "#c832b3"
light-magenta = "#e09a83"
light-cyan = "#db7e71"
