inherits = "base16_default"
[pallete]

default = "#132d3f"
black = "#88cde1"
red = "#9edae6"
green = "#95d1e4"
yellow = "#abdaea"
blue = "#b9e2ed"
magenta = "#bae1ed"
cyan = "#deebef"
gray = "#9ba4a7"
light-red = "#88cde1"
light-green = "#9edae6"
light-yellow = "#95d1e4"
light-blue = "#abdaea"
light-magenta = "#b9e2ed"
light-cyan = "#bae1ed"
