inherits = "base16_default"
[pallete]

default = "#0f0f0f"
black = "#94bf2f"
red = "#a3b82d"
green = "#dcc876"
yellow = "#efddc2"
blue = "#f1dec7"
magenta = "#e5f0c6"
cyan = "#e8e7e5"
gray = "#a2a1a0"
light-red = "#94bf2f"
light-green = "#a3b82d"
light-yellow = "#dcc876"
light-blue = "#efddc2"
light-magenta = "#f1dec7"
light-cyan = "#e5f0c6"
