inherits = "base16_default"
[pallete]

default = "#282828"
black = "#cc241d"
red = "#d79921"
green = "#b58900"
yellow = "#458588"
blue = "#b16286"
magenta = "#689d6a"
cyan = "#a89984"
gray = "#928374"
light-red = "#cc241d"
light-green = "#d79921"
light-yellow = "#b58900"
light-blue = "#458588"
light-magenta = "#b16286"
light-cyan = "#689d6a"
