inherits = "base16_default"
[pallete]

default = "#0c0c0d"
black = "#3b2594"
red = "#b82e6f"
green = "#27619d"
yellow = "#2e64bb"
blue = "#ce3eb1"
magenta = "#4292cf"
cyan = "#aec7df"
gray = "#798b9c"
light-red = "#3b2594"
light-green = "#b82e6f"
light-yellow = "#27619d"
light-blue = "#2e64bb"
light-magenta = "#ce3eb1"
light-cyan = "#4292cf"
