inherits = "base16_default"
[pallete]

default = "#0f1315"
black = "#ae6c2b"
red = "#a35728"
green = "#ba6d2e"
yellow = "#ce953b"
blue = "#d69e5c"
magenta = "#2e89b9"
cyan = "#cbc4c2"
gray = "#8e8987"
light-red = "#ae6c2b"
light-green = "#a35728"
light-yellow = "#ba6d2e"
light-blue = "#ce953b"
light-magenta = "#d69e5c"
light-cyan = "#2e89b9"
