#!/bin/sh
saturation=""
file=""
while getopts "f:s:" opt; do
    case $opt in
    s) saturation=$OPTARG;;
    f) file=$OPTARG;;
    ?) echo "invalid switch\n"; exit;;
    esac
done
if [ ! -n "$file" ]; then
    exit
fi

cp $file ~/bg/bg1.png
echo "new background: $file"

if test -z "$saturation"; then
    echo "no saturation given"
    wal -n -i ~/bg/bg1.png
else
    echo "saturation $saturation"
    wal -n -i ~/bg/bg1.png --saturate $saturation
fi

echo "background_opacity 0.75" >> ~/.cache/wal/colors-kitty.conf
pywal-extender
cd ~/.source/st/
sudo make clean install
~/.spicetify/spicetify apply

