# theme = "catppuccin_macchiato"
# theme = "molokai"
# theme = "monokai_pro_machine"
# theme = "nightfox"
# theme = "gruvbox"
# theme = "night_owl"

# theme = "sonokai_default"
# theme = "catppuccin_mocha"
# theme = "gruvbox"
# theme = "kanagawa"
theme = "molokai"

[editor]
line-number = "relative"
auto-format = false

[keys.normal]
C-e = "scroll_down"
C-y = "scroll_up"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
C = ":run-shell-command cmake --build build"
c = ":run-shell-command make"
