# theme = "catppuccin_macchiato"
# theme = "molokai"
# theme = "monokai_pro_machine"
# theme = "nightfox"
# theme = "gruvbox"
# theme = "night_owl"

# theme = "sonokai_default"
# theme = "catppuccin_mocha"
# theme = "gruvbox"
# theme = "molokai"
# theme = "trans"
# theme = "wal"
# theme = "hex_steel"
# theme = "nord"
# theme = "nord-opaque"
# theme = "nord-night"
# theme = "amberwood"
# theme = "ayu_dark"
# theme = "ayu_mirage"
theme = "bill"

[editor]
line-number = "relative"
auto-format = false
cursorline = false
bufferline = "multiple"

[keys.normal]
C-e = "scroll_down"
C-y = "scroll_up"
esc = ["collapse_selection", "keep_primary_selection"]
C-t = [":new", ":insert-output bash", ":buffer-close!", ":redraw"]

[keys.normal."space"]
C = ":run-shell-command cmake --build build"
c = ":run-shell-command make"

[keys.normal.t]
l = ":buffer-next"
n = ":buffer-next"
h = ":buffer-previous"
p = ":buffer-previous"
c = ":buffer-close"

[editor.soft-wrap]
enable = false
